import { test, expect } from '@playwright/test';

/**
 * ⚠️  AUTO-GENERATED by AI-QA-AGENT
 * Every selector below was decided by Gemini AI from live DOM.
 * Generated: 2026-03-26T10:13:16.876Z
 */

test('AI Generated Test', async ({ page }) => {

  // 🤖 AI Step: Open the login page
  // 🔧 Tool: playwright_navigate | Params: {"url":"https://qahmis.digicure.ai/#/authentication/login"}
  await page.goto('https://qahmis.digicure.ai/#/authentication/login');

  // 🤖 AI Step: Maximize the browser window
  // 🔧 Tool: playwright_maximize | Params: undefined
  await page.setViewportSize({ width: 1920, height: 1080 });

  // 🤖 AI Step: Enter 'relareg' in the Username field
  // 🔧 Tool: playwright_fill | Params: {"selector":"#username","value":"relareg"}
  await page.locator('#username').fill('relareg');

  // 🤖 AI Step: Enter 'Welcome@01' in the Password field
  // 🔧 Tool: playwright_fill | Params: {"selector":"#password","value":"Welcome@01"}
  await page.locator('#password').fill('Welcome@01');

  // 🤖 AI Step: Enter '1234' in the Captcha field
  // 🔧 Tool: playwright_fill | Params: {"selector":"#captchaconfirm","value":"1234"}
  await page.locator('#captchaconfirm').fill('1234');

  // 🤖 AI Step: Click on the 'Sign In' button
  // 🔧 Tool: playwright_click | Params: {"selector":"button[type='submit'].btn.btn-common"}
  await page.locator('button[type='submit'].btn.btn-common').click();

  // 🤖 AI Step: Wait for the 'Select Institutions' modal popup to appear
  // 🔧 Tool: playwright_click | Params: {"selector":"button:has-text('Select Institutions')"}
  await page.locator('button:has-text('Select Institutions')').click();

  // 🤖 AI Step: Click on the 'Department Selection' dropdown
  // 🔧 Tool: playwright_click | Params: {"selector":"select[name='departId']"}
  await page.locator('select[name='departId']').click();

  // 🤖 AI Step: Select 'General Medicine' from the dropdown list
  // 🔧 Tool: playwright_select_option | Params: {"selector":"select[name='departId']","value":"General Medicine"}
  await page.locator('select[name='departId']').selectOption('General Medicine');

  // 🤖 AI Step: Click on the 'Save' button
  // 🔧 Tool: playwright_click | Params: {"selector":"button:has-text('Save')"}
  await page.locator('button:has-text('Save')').click();

});
