export class ScriptBuilder {
  build(executedSteps: any[]): string {
    let code = `import { test, expect } from '@playwright/test';\n\n`;
    code += `/**\n * ⚠️  AUTO-GENERATED by AI-QA-AGENT\n`;
    code += ` * Every selector below was decided by Gemini AI from live DOM.\n`;
    code += ` * Generated: ${new Date().toISOString()}\n */\n\n`;
    code += `test('AI Generated Test', async ({ page }) => {\n`;

    for (const { step, toolCall } of executedSteps) {
      code += `\n  // 🤖 AI Step: ${step.description}\n`;
      code += `  // 🔧 Tool: ${toolCall.tool} | Params: ${JSON.stringify(toolCall.params)}\n`;

      switch (toolCall.tool) {
        case "playwright_navigate":
          code += `  await page.goto('${toolCall.params.url}');\n`;
          break;

        case "playwright_click":
          code += `  await page.locator('${toolCall.params.selector}').click();\n`;
          break;

        case "playwright_fill":
          code += `  await page.locator('${toolCall.params.selector}').fill('${toolCall.params.value}');\n`;
          break;

        case "playwright_select_option":
          code += `  await page.locator('${toolCall.params.selector}').selectOption('${toolCall.params.value}');\n`;
          break;

        case "playwright_hover":
          code += `  await page.locator('${toolCall.params.selector}').hover();\n`;
          break;

        case "playwright_maximize":
          code += `  await page.setViewportSize({ width: 1920, height: 1080 });\n`;
          break;

        case "playwright_screenshot":
          code += `  await page.screenshot({ path: '${toolCall.params.name}', fullPage: true });\n`;
          break;

        case "playwright_wait_for_url":
          code += `  await page.waitForURL('${toolCall.params.url}');\n`;
          break;

        case "playwright_evaluate":
          code += `  await page.evaluate(() => { ${toolCall.params.script} });\n`;
          break;

        default:
          code += `  // ⚠️ Unknown tool: ${toolCall.tool}\n`;
      }
    }

    code += `\n});\n`;
    return code;
  }
}
